basePath: /v1
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for GopherSocial, a social network for gophers
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GopherSocial
paths: {}
securityDefinitions:
  ApiKeyAuth:
    description: Description for the tool
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
